server:
  port: 9000
  servlet:
    context-path: /pg07

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: 962464HeLei
    jdbcUrl: jdbc:mysql://localhost:3306/scsp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
  devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        poll-interval: 5000
        quiet-period: 1000


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.pg7.scsp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    org.pg7.scsp: debug